version: '3.8'

services:
  zabbix-mysql:
    image: mysql:8
    container_name: zabbix-mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /docker/zabbix/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8
      --collation-server=utf8_bin
    networks:
      - zabbix

  zabbix-snmptraps:
    image: zabbix/zabbix-snmptraps
    container_name: zabbix-snmptraps
    restart: always
    ports:
      - "162:1162/udp"
    volumes:
      - /docker/zabbix/snmptraps:/var/lib/zabbix/snmptraps:rw
      - /docker/zabbix/mibs:/usr/share/snmp/mibs:ro
    networks:
      - zabbix

  zabbix-server:
    image: zabbix/zabbix-server-mysql
    container_name: zabbix-server
    restart: always
    ports:
      - "10051:10051"
    environment:
      DB_SERVER_HOST: zabbix-mysql
      DB_SERVER_PORT: "3306"
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      ZBX_ENABLE_SNMP_TRAPS: "true"
    networks:
      - zabbix
    volumes:
      - zabbix-snmptraps:/var/lib/zabbix/snmptraps

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql
    container_name: zabbix-web
    restart: always
    ports:
      - "80:8080"
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: zabbix-mysql
      DB_SERVER_PORT: "3306"
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      PHP_TZ: America/Sao_Paulo
    networks:
      - zabbix

  zabbix-agent:
    image: zabbix/zabbix-agent
    container_name: zabbix-agent
    restart: always
    privileged: true
    networks:
      - zabbix
    depends_on:
      - zabbix-server

networks:
  zabbix:
    driver: bridge

volumes:
  zabbix-snmptraps:
    external: true